#!/bin/bash

#install zsh
sudo apt-get install zsh

# Load theme repo
git clone --recursive https://github.com/paradox460/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Copy file config
cp .zpreztorc ~/
cp .zshrc ~/ 

# Install font

#set default shell
sudo chsh -s /bin/zsh
